---
title: "scratchwork"
author: "Ishan Bhatt"
date: "3/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
library(ggthemes)
library(sp)
library(sf)

```

```{r}

data <- read_csv("raw-data/property-2016-2021.csv") 

```

## Residential Categorizing

```{r}

housing_indicators <- c(">8-UNIT-APT",
"4-8-UNIT-APT",
"AFFORDABLE APT",
"CNDO LUX",
"CNDO-RES-PKG",	
"CONDO-BLDG",
"CONDO-PKG-SP",	
"CONDOMINIUM",
"Housing",	
"INDUST-CONDO",	
"MULT-RES->8 APT",	
"MULT-RES-1FAM",	
"MULT-RES-2FAM",	
"MULT-RES-3FAM",	
"MULT-RES-4-8-APT",	
"MULTI UNIT CNDO",	
"MULTIPLE-RES",	
"MXD >8-UNIT-APT",	
"MXD 4-8-UNIT-APT",
"MXD CONDOMINIUM",	
"MXD THREE-FM-RES",	
"RETAIL-CONDO",	
"SINGLE FAM W/AUXILIARY APT",
"SNGL-FAM-RES",	
"TWO-FAM-RES")


high_density_indicators <- c(">8-UNIT-APT",
"4-8-UNIT-APT",
"AFFORDABLE APT",
"CNDO LUX",
"CNDO-RES-PKG",	
"CONDO-BLDG",
"CONDO-PKG-SP",	
"CONDOMINIUM",
"INDUST-CONDO",	
"MULT-RES->8 APT",	
"MULT-RES-1FAM",	
"MULT-RES-2FAM",	
"MULT-RES-3FAM",	
"MULT-RES-4-8-APT",	
"MULTI UNIT CNDO",	
"MULTIPLE-RES",	
"MXD >8-UNIT-APT",	
"MXD 4-8-UNIT-APT",
"MXD CONDOMINIUM",	
"MXD THREE-FM-RES",	
"RETAIL-CONDO")

# Indicator Variable for residential and density

housing_data <- data %>%
  mutate(residential = if_else(PropertyClass %in% housing_indicators, 1, 0)) %>%
  mutate(high_density = if_else(PropertyClass %in% high_density_indicators, 1, 0)) %>%
  separate(Address, c("address", "coord"), sep = "[(]") %>%
  filter(YearOfAssessment < 2022) %>%
  filter(! is.na(AssessedValue))

housing_data$coord <- str_remove(housing_data$coord, "[)]")

housing_data <- housing_data %>%
  separate(coord, c("lat", "long"), sep = "[,]", remove = F)
housing_data$AssessedValue <- as.numeric(housing_data$AssessedValue)


housing_data$lat <- as.numeric(housing_data$lat)
housing_data$long <- as.numeric(housing_data$long)

housing_data <- housing_data %>%
  filter(!is.na(lat)) %>%
  mutate(price_increase = AssessedValue - PreviousAssessedValue)

spatial_housing <- housing_data
coordinates(spatial_housing) <- cbind(spatial_housing$long, spatial_housing$lat)

housing_data <- within(housing_data, value_quartile <- as.integer(cut(AssessedValue, quantile(AssessedValue, probs=0:4/4), include.lowest=TRUE)))

write.csv(housing_data, "clean-data/property_clean.csv")

```

## Small Data

```{r}

small_data <- housing_data %>%
  filter(residential == 1) %>%
  select(lat, long, GISID, StateClassCode, AssessedValue, PreviousAssessedValue)

write.csv(small_data, "clean-data/small_data.csv")

```

## Pricing Statistics

```{r}

price_stats <- housing_data %>%
  filter(residential == 1) %>%
  group_by(YearOfAssessment, high_density) %>%
  summarize(value = mean(AssessedValue), 
            previous_value = mean(PreviousAssessedValue), 
            sale_price = mean(SalePrice),
            .groups = "keep") %>%
  mutate(housing_style = if_else(high_density == 1, "High Density", "Low Density"))

ggplot(price_stats, aes(x = YearOfAssessment, y = value, color = as.factor(housing_style))) +
  geom_line() + 
  theme_light() +
  labs(
    color = "Housing Style",
    x = "Year of Assessment",
    y = "Mean Assessed Value",
    title = "Residential Property Values by Year"
    # subtitle = "Dashed line is previous value assesment, dotted is original sale price"
  ) + 
  # geom_line(aes(x = YearOfAssessment, y = previous_value), linetype = "dashed") + 
  # geom_line(aes(x = YearOfAssessment, y = sale_price), linetype = "dotted") +
  scale_colour_manual(values = c("red", "blue"))
  

```

## Checking Duplicates

```{r}

dupli <- housing_data %>%
  distinct(address, YearOfAssessment, BldgNum, Unit)

# Units was the key swing

```


## Development

```{r}


new <- st_read("raw-data/boundaries.shp", package = "sp")


```


